steps:

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/black-sanctum-292019/face-detection:1.0', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/black-sanctum-292019/face-detection:1.0']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'demo-apps-cloudrun', '--image', 'gcr.io/black-sanctum-292019/face-detection:1.0', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/black-sanctum-292019/face-detection:1.0
